//************ sym.h **************
#define symSYMMAX         50
#define symEOF             0
#define symerror           1
#define symIDENTIFIER      2
#define symNUMBER          3
#define symPLUS            4
#define symMINUS           5
#define symMUL             6
#define symDIV             7
#define symEQ              8
#define symNEQ             9
#define symLESS           10
#define symLEQ            11
#define symGREATER        12
#define symGEQ            13
#define symLPAREN         14
#define symRPAREN         15
#define symCOMMA          16
#define symSEMI           17 
#define symPERIOD         18
#define symBEGIN          19
#define symEND            20
#define symIF             21
#define symTHEN           22
#define symWHILE          23
#define symDO             24
#define symREAD           25
#define symWRITE          26
#define symIDENTIFIERLIST 27
#define symCALL           28
#define symCONST          29
#define symINT            30
#define symPROCEDURE      31
#define symPROGRAM        32
#define symSTRING         33
#define symELSE			  34
#define symMOD			  35
#define symASSIGN		  36
#define symCOMMENT        37
#define symINC            38
#define symDEC			  39
#define symSHL			  40
#define symSHR			  41
#define symOR			  42
#define symLOR            43
#define symAND			  44
#define symLAND           45
#define symXOR            46 
#define symLBRACE         47
#define symRBRACE         48
#define symHEAD           49 
